import type { ModelProfile } from "./model-profile.types.ts";
import { OPENAI_GPT_5_2_CHAT_URL, OPENAI_GPT_5_2_URL, OPENAI_MODELS_URL } from "./model-urls.ts";

/** GPT-5.x ChatGPT browser model profiles. */
export const OPENAI_GPT5_MODEL_PROFILES: ModelProfile[] = [
  {
    id: "gpt-5.5-pro",
    label: "GPT-5.5 Pro",
    provider: "openai",
    aliases: ["gpt-5.5 pro", "gpt 5.5 pro", "pro", "model-switcher-gpt-5-5-pro"],
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    sourceUrl: OPENAI_MODELS_URL,
    note: "ChatGPT browser UI label observed from the model picker.",
  },
  {
    id: "gpt-5.5-thinking",
    label: "GPT-5.5 Thinking",
    provider: "openai",
    aliases: [
      "gpt-5.5 thinking",
      "gpt 5.5 thinking",
      "thinking",
      "model-switcher-gpt-5-5-thinking",
    ],
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    sourceUrl: OPENAI_MODELS_URL,
    note: "ChatGPT browser UI label observed from the model picker.",
  },
  {
    id: "gpt-5.3-instant",
    label: "GPT-5.3 Instant",
    provider: "openai",
    aliases: ["gpt-5.3 instant", "gpt 5.3 instant", "instant", "model-switcher-gpt-5-3"],
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    sourceUrl: OPENAI_MODELS_URL,
    note: "ChatGPT browser UI label observed from the model picker.",
  },
  {
    id: "gpt-5.2-chat-latest",
    label: "GPT-5.2 Chat",
    provider: "openai",
    aliases: ["gpt-5.2", "gpt 5.2", "gpt-5.2 chat", "chatgpt gpt-5.2", "gpt-5-2"],
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    sourceUrl: OPENAI_GPT_5_2_CHAT_URL,
    note: "ChatGPT browser model alias, not the larger API flagship context.",
  },
  {
    id: "gpt-5.2",
    label: "GPT-5.2 API",
    provider: "openai",
    aliases: ["api:gpt-5.2", "gpt-5.2 api", "openai gpt-5.2"],
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    sourceUrl: OPENAI_GPT_5_2_URL,
  },
  {
    id: "gpt-5.1-chat-latest",
    label: "GPT-5.1 Chat",
    provider: "openai",
    aliases: ["gpt-5.1", "gpt 5.1", "gpt-5.1 chat", "chatgpt gpt-5.1", "gpt-5-1"],
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    sourceUrl: "https://platform.openai.com/docs/models/gpt-5.1-chat-latest",
  },
  {
    id: "gpt-5-chat-latest",
    label: "GPT-5 Chat",
    provider: "openai",
    aliases: ["gpt-5", "gpt 5", "gpt-5 chat", "chatgpt gpt-5", "gpt-5-0"],
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    sourceUrl: "https://platform.openai.com/docs/models/gpt-5-chat-latest",
  },
];
